insert into topics (level, prev_id, title, user_id) values 
('0', NULL, 'Me and Friends',1),
('1', '1', 'This explains the beginning of my life all',2),
('0', NULL, 'Another one',3),
('1', '2', 'What is it',2),
('1', '3',  'My life from the beginning was very fun',2),
('1', '3', 'Why am i that good',2),
('2', '5', 'In order to go',1),
('3', '7', 'Decided to stay here',1),
('0', NULL, 'the way to the end of my life.',1),
('2', '2', 'bla bla bla',1),
('1', '9',  'as I grew up living with my moms',2),
('2', '11',  'friend and my friend. But there were a',3),
('2', '11', 'Right now',1),
('2', '2', 'lot of fights and I was very hyper',1),
('1', '3', 'Maybe another',2),
('2', '6',  'back then. I have ADHD so back then',1),
('2', '5',  'when I was little; I was very hyper',3),
('0', NULL, 'What was it',1),
('1', '18',  'and would not stop moving around the place. I',3);
